### PR TITLE
Add browser data checkbox, remove browser history/cookies checkboxes, add shellbags, RDPCache, and network share functionality, updated MRU-Info script

### PR DESCRIPTION
**Pull request by adeschene**
- Removed the Browser History and Browser Cookies checkboxes
- Added a Browser Data checkbox
- Removed Browser-History.ps1
- Updated relevant code in OneForAll.ps1
- The Browser Data checkbox now leads to the Browser-Data-Retrieval function being called directly
- Rearranged a couple checkboxes to reflect their location in the GUI better
- Added functionality for Shellbags, RDPCache, and Network Share Info scripts.
- They may not be getting all of the desired information, but they're at least a good start
- More info on these will need to be gathered during the meeting with sponsors
- Also added a small check to Jump-Lists
- Made MRU-Info.ps1 collect MRU registry keys for each user instead of just the current user.

### CODE REVIEW

**Comment by adeschene** [comment]
I meant to break this up into a couple separate pull requests but I forgot to make a new branch when I started making the second set of changes. Let me know if you see this as an issue, I can try to revert the last couple of commits and then put them on a new branch...although I'd have to look up how to do that.

**Review by nfriedrich — APPROVED** [review]
No problems here.
Have you looked at [Shadowspawn](https://github.com/candera/shadowspawn) for the shellbags? It's dependent on the Visual C++ 8.0 runtime, but that can be silently installed. However, I don't know if installing stuff is an issue or not.

**Comment by adeschene** [comment]
> No problems here.
> Have you looked at [Shadowspawn](https://github.com/candera/shadowspawn) for the shellbags? It's dependent on the Visual C++ 8.0 runtime, but that can be silently installed. However, I don't know if installing stuff is an issue or not.

Interesting, I hadn't heard of that.
But yeah, the main problem is that we can't install anything (afaik), otherwise there is a shellbag extractor utility that we could just use, but yeah.

**Comment by nfriedrich** [comment]
Ouch yeah, maybe left as an option in a future release then.

**Pull request merged**
