### PR TITLE
Add results page, data packaging, etc.

### PR DESCRIPTION
**Pull request by adeschene**
- Added a results page that writes out the current process as it's being done, then shows the elapsed time of the scan and finishes.
- The results page has 3 buttons that allow the user to go back to the main menu, view the output file in the explorer, or exit the program. These buttons are disabled while a scan is running.
- Added the Package-Output.ps1 script, which allows the output files/folders to be packaged up into either a .zip or .vhdx depending on the user selection.
- Changed the User-Profiles.ps1 script because it was saving/loading profiles from the output folder, which was causing errors when the output folder was anything expect the default location.
- Updated the Jump-Lists.ps1 script to create a less verbose folder hierarchy.
- Updated ~IMPORTS.ps1 to include the new script I added.
- Updated output location to create an output folder in the chosen location to save everything to, and to bring up a messsage box to instruct the user if they try to use a local output location.
- Added menu transitions for the results page to Menu-Transitions.ps1.
-  Updated Data recovery labels and such in order to avoid a conflict with the last merge.

### CODE REVIEW

**Comment by adeschene** [comment]
This is unfortunately a large pull with a lot of changes.
Ideally, I would've done things more incrementally, but I'm not great at that, and it's all mashed together.
I can try to separate things out if that seems like a worthwhile effort, but worse comes to worst, we can always roll back the changes. Everything should be working well though, I did a lot of testing and I think I covered my bases.
Mainly, I'd just like to get this in before the feature freeze and we can change it at our leisure later on down the road.

Let me know what you think!

**Comment by nfriedrich** [comment]
No worries. It's fantastic, just gave it a run. One problem: saving profiles worked how I think it supposed to but loading them only gave me blank checks.

**Comment by adeschene** [comment]
Yeah, that's an issue I've been having with the profiles since they were added, as in before I changed anything.
Did that not happen for you before these changes?

**Comment by adeschene** [comment]
> No worries. It's fantastic, just gave it a run. One problem: saving profiles worked how I think it supposed to but loading them only gave me blank checks.

Yeah, that's an issue I've been having with the profiles since they were added, as in before I changed anything.
Did that not happen for you before these changes?

**Comment by nfriedrich** [comment]
I only tested the one that sets everything to off, so I gueess it probably didn't work fully. I'll go ahead and merge everything then and we'll fix it after the freeze.

**Comment by adeschene** [comment]
> I only tested the one that sets everything to off, so I gueess it probably didn't work fully. I'll go ahead and merge everything then and we'll fix it after the freeze.

Sounds good. I meant to tell Kobe about it but never got around to it.

**Pull request merged**
